name: Build macOS Executable with PyInstaller

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  workflow_dispatch:  # Allow manual runs

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'  # Adjust based on your project requirements

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed build_exe.py  # Adjust options as needed

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/*  # Path to the built executable
